// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package migrate

import (
	"bytes"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	monitoringv1 "github.com/GoogleCloudPlatform/prometheus-engine/pkg/operator/apis/monitoring/v1"
	"github.com/google/go-cmp/cmp"
	pomonitoringv1 "github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1"
	prommodel "github.com/prometheus/common/model"
	"github.com/prometheus/prometheus/config"
	promk8s "github.com/prometheus/prometheus/discovery/kubernetes"
	"github.com/prometheus/prometheus/model/relabel"
	"github.com/prometheus/prometheus/util/strutil"
	"gopkg.in/yaml.v2"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/intstr"
	"k8s.io/utils/ptr"
	k8syaml "sigs.k8s.io/yaml"
)

// 1. Constants.
const (
	metaPodLabelPrefix     = "__meta_kubernetes_pod_label_"
	metaServiceLabelPrefix = "__meta_kubernetes_service_label_"
)

// 2. Low-Level Relabel Helpers.

// newPORelabelRule constructs a new Prometheus Operator style relabel rule.
func newPORelabelRule(action relabel.Action, src []string, target string, regex string, repl string) *relabel.Config {
	var srcNames prommodel.LabelNames
	for _, s := range src {
		srcNames = append(srcNames, prommodel.LabelName(s))
	}
	return &relabel.Config{
		Action:       action,
		SourceLabels: srcNames,
		Separator:    ";",
		TargetLabel:  target,
		Regex:        relabel.MustNewRegexp(regex),
		Replacement:  repl,
	}
}

// isGMPInternalRelabelRule returns true for relabel rules injected solely for GMP Monarch runtime.
func isGMPInternalRelabelRule(r *relabel.Config) bool {
	if r == nil {
		return false
	}
	switch r.TargetLabel {
	case "project_id", "location", "cluster", "top_level_controller_name", "top_level_controller_type", "__tmp_instance":
		return true
	case "job":
		if len(r.SourceLabels) == 0 && r.Action == relabel.Replace {
			return true
		}
	case "instance":
		if slices.Contains(r.SourceLabels, "__tmp_instance") {
			return true
		}
	case "__address__":
		if len(r.SourceLabels) == 1 && r.SourceLabels[0] == "__meta_kubernetes_pod_ip" {
			return true
		}
	}

	if r.Action == relabel.LabelDrop && r.Regex.Regexp != nil && r.Regex.String() == "container" {
		return true
	}

	if len(r.SourceLabels) == 1 && r.SourceLabels[0] == "__meta_kubernetes_namespace" && r.Action == relabel.Keep {
		return true
	}

	return false
}

// 3. Relabel Pipeline Stage Builders.

// buildInitialJobRule creates the rule tracking the job label into __tmp_prometheus_job_name.
func buildInitialJobRule() *relabel.Config {
	return newPORelabelRule(relabel.Replace, []string{"job"}, "__tmp_prometheus_job_name", "(.*)", "$1")
}

// extractPhaseDropRule extracts the pod phase drop rule if emitted by GMP.
func extractPhaseDropRule(gmpRelabelConfigs []*relabel.Config) []*relabel.Config {
	var out []*relabel.Config
	for _, r := range gmpRelabelConfigs {
		if r == nil {
			continue
		}
		if len(r.SourceLabels) == 1 && r.SourceLabels[0] == "__meta_kubernetes_pod_phase" && r.Action == relabel.Drop {
			out = append(out, newPORelabelRule(relabel.Drop, []string{"__meta_kubernetes_pod_phase"}, "", r.Regex.String(), "$1"))
		}
	}
	return out
}

// extractFromPodRelabelRules extracts pod target labels generated by GMP's fromPod compiler.
func extractFromPodRelabelRules(gmpRelabelConfigs []*relabel.Config) []*relabel.Config {
	var out []*relabel.Config
	for _, r := range gmpRelabelConfigs {
		if r == nil {
			continue
		}
		if len(r.SourceLabels) == 1 && strings.HasPrefix(string(r.SourceLabels[0]), metaPodLabelPrefix) && r.Action == relabel.Replace {
			out = append(out, newPORelabelRule(relabel.Replace, []string{string(r.SourceLabels[0])}, r.TargetLabel, "(.+)", "${1}"))
		}
	}
	return out
}

// buildPodRelabelRules constructs the standard PodMonitor target relabeling pipeline:
// Phase Drop -> Port Keep -> Metadata Mappings (namespace, container, pod) -> Extracted Pod Target Labels.
func buildPodRelabelRules(gmpRelabelConfigs []*relabel.Config, endpointPort string) []*relabel.Config {
	var out []*relabel.Config

	// 1. Phase Drop rule (if emitted by GMP).
	out = append(out, extractPhaseDropRule(gmpRelabelConfigs)...)

	// 2. Port Keep and Metadata replacements.
	// TODO: Add support for node, cluster, or namespace metadata label extraction if future upstream test fixtures
	// evaluate attachMetadata or cluster-scoped PodMonitoring against golden files.
	out = append(out,
		newPORelabelRule(relabel.Keep, []string{"__meta_kubernetes_pod_container_port_name"}, "", endpointPort, "$1"),
		newPORelabelRule(relabel.Replace, []string{"__meta_kubernetes_namespace"}, "namespace", "(.*)", "$1"),
		newPORelabelRule(relabel.Replace, []string{"__meta_kubernetes_pod_container_name"}, "container", "(.*)", "$1"),
		newPORelabelRule(relabel.Replace, []string{"__meta_kubernetes_pod_name"}, "pod", "(.*)", "$1"),
	)

	// 3. Extract Pod target labels generated by GMP's fromPod compiler.
	out = append(out, extractFromPodRelabelRules(gmpRelabelConfigs)...)

	return out
}

// buildEndpointRelabelRules constructs the standard ServiceMonitor target relabeling pipeline:
// Port Keep -> Target Kind Mappings (Node, Pod) -> Metadata Mappings -> Phase Drop -> Target Labels.
func buildEndpointRelabelRules(gmpRelabelConfigs, gmpMetricRelabelConfigs, expectedRelabelConfigs []*relabel.Config, endpointPort string, svcLabels map[string]string) []*relabel.Config {
	var out []*relabel.Config

	// 1. Port Keep, Address target kind mappings, and Metadata replacements.
	out = append(out,
		newPORelabelRule(relabel.Keep, []string{"__meta_kubernetes_endpoint_port_name"}, "", endpointPort, "$1"),
		newPORelabelRule(relabel.Replace, []string{"__meta_kubernetes_endpoint_address_target_kind", "__meta_kubernetes_endpoint_address_target_name"}, "node", "Node;(.*)", "${1}"),
		newPORelabelRule(relabel.Replace, []string{"__meta_kubernetes_endpoint_address_target_kind", "__meta_kubernetes_endpoint_address_target_name"}, "pod", "Pod;(.*)", "${1}"),
		newPORelabelRule(relabel.Replace, []string{"__meta_kubernetes_namespace"}, "namespace", "(.*)", "$1"),
		newPORelabelRule(relabel.Replace, []string{"__meta_kubernetes_service_name"}, "service", "(.*)", "$1"),
		newPORelabelRule(relabel.Replace, []string{"__meta_kubernetes_pod_name"}, "pod", "(.*)", "$1"),
		newPORelabelRule(relabel.Replace, []string{"__meta_kubernetes_pod_container_name"}, "container", "(.*)", "$1"),
	)

	// 2. Phase Drop rule (if emitted by GMP).
	out = append(out, extractPhaseDropRule(gmpRelabelConfigs)...)

	// 3. Extract Pod target labels if generated by GMP's fromPod compiler.
	out = append(out, extractFromPodRelabelRules(gmpRelabelConfigs)...)

	// 4. Extract Service target labels migrated by gmp-migrate into metric relabel configs.
	// Because GMP uses pod discovery, gmp-migrate converts ServiceMonitor.spec.targetLabels into static
	// metricRelabeling rules (sorted alphabetically for determinism). We verify that gmpMetricRelabelConfigs
	// contains each expected service target label from expectedRelabelConfigs and map them in expected order.
	if svcLabels != nil {
		for _, expRule := range expectedRelabelConfigs {
			if len(expRule.SourceLabels) == 1 && strings.HasPrefix(string(expRule.SourceLabels[0]), metaServiceLabelPrefix) {
				rawKey := strings.TrimPrefix(string(expRule.SourceLabels[0]), metaServiceLabelPrefix)
				target := strutil.SanitizeLabelName(rawKey)
				if protectedLabels[target] {
					target = "exported_" + target
				}
				for _, r := range gmpMetricRelabelConfigs {
					if r == nil {
						continue
					}
					if len(r.SourceLabels) == 0 && r.Action == relabel.Replace && r.TargetLabel == target && r.Replacement == svcLabels[rawKey] {
						out = append(out, newPORelabelRule(relabel.Replace, []string{metaServiceLabelPrefix + rawKey}, expRule.TargetLabel, "(.+)", "${1}"))
						break
					}
				}
			}
		}
	}

	return out
}

// extractCustomRelabelRules filters out GMP internal Monarch rules and preserves user-defined relabel configs.
//
// TODO: If future upstream test cases introduce custom pre-scrape relabelings that gmp-migrate converts into
// metricRelabeling or targetLabels, add normalization logic here to map them back to expected target relabelings.
func extractCustomRelabelRules(gmpRelabelConfigs []*relabel.Config) []*relabel.Config {
	var out []*relabel.Config
	for _, r := range gmpRelabelConfigs {
		if r == nil {
			continue
		}
		if isGMPInternalRelabelRule(r) {
			continue
		}
		if len(r.SourceLabels) == 1 {
			src := string(r.SourceLabels[0])
			if src == "__meta_kubernetes_pod_phase" || src == "__meta_kubernetes_pod_container_port_name" || src == "__meta_kubernetes_namespace" || strings.HasPrefix(src, metaPodLabelPrefix) {
				continue
			}
		}
		var src []string
		for _, s := range r.SourceLabels {
			src = append(src, string(s))
		}
		regexStr := "(.*)"
		if r.Regex.Regexp != nil && r.Regex.String() != "" {
			regexStr = r.Regex.String()
		}
		replStr := "$1"
		if r.Replacement != "" {
			replStr = r.Replacement
		}
		out = append(out, newPORelabelRule(r.Action, src, r.TargetLabel, regexStr, replStr))
	}
	return out
}

// buildTrailingRelabelRules constructs trailing job, endpoint, and sharding hashmod rules.
func buildTrailingRelabelRules(role promk8s.Role, namespace, name, endpointPort string) []*relabel.Config {
	var out []*relabel.Config
	if role == promk8s.RoleEndpoint {
		out = append(out, newPORelabelRule(relabel.Replace, []string{"__meta_kubernetes_service_name"}, "job", "(.*)", "${1}"))
	} else {
		out = append(out, newPORelabelRule(relabel.Replace, nil, "job", "(.*)", fmt.Sprintf("%s/%s", namespace, name)))
	}
	out = append(out, newPORelabelRule(relabel.Replace, nil, "endpoint", "(.*)", endpointPort))

	hashRule := newPORelabelRule(relabel.HashMod, []string{"__address__"}, "__tmp_hash", "(.*)", "$1")
	hashRule.Modulus = 1
	out = append(out,
		hashRule,
		newPORelabelRule(relabel.Keep, []string{"__tmp_hash"}, "", "$(SHARD)", "$1"),
	)
	return out
}

// 4. ScrapeConfig Normalization Engine.

// normalizeTargetRelabelConfigs builds the standard Prometheus Operator target relabeling pipeline.
func normalizeTargetRelabelConfigs(gmpRelabelConfigs, gmpMetricRelabelConfigs, expectedRelabelConfigs []*relabel.Config, role promk8s.Role, namespace, name, endpointPort string, svcLabels map[string]string) []*relabel.Config {
	var out []*relabel.Config

	// Step 1: Initial job name tracking rule.
	out = append(out, buildInitialJobRule())

	// Step 2: Role-specific discovery rules.
	if role == promk8s.RolePod {
		out = append(out, buildPodRelabelRules(gmpRelabelConfigs, endpointPort)...)
	} else {
		out = append(out, buildEndpointRelabelRules(gmpRelabelConfigs, gmpMetricRelabelConfigs, expectedRelabelConfigs, endpointPort, svcLabels)...)
	}

	// Step 3: Custom user-defined relabel rules.
	out = append(out, extractCustomRelabelRules(gmpRelabelConfigs)...)

	// Step 4: Trailing job, endpoint, and sharding hashmod rules.
	out = append(out, buildTrailingRelabelRules(role, namespace, name, endpointPort)...)

	return out
}

// normalizeGMPScrapeConfig transforms a GMP-generated ScrapeConfig so that it adopts
// upstream Prometheus Operator standard infrastructure conventions for 1:1 comparison.
//
// TODO: Support dynamic endpoint port resolution per-scrape-config index for complex multi-endpoint resources
// with heterogeneous port types if future multi-endpoint golden test cases are added.
func normalizeGMPScrapeConfig(gmp *config.ScrapeConfig, expectedPO *config.ScrapeConfig, role promk8s.Role, namespace, name, endpointPort string, svcLabels map[string]string) *config.ScrapeConfig {
	if gmp == nil || expectedPO == nil {
		return nil
	}
	out := &config.ScrapeConfig{
		// Standard Prometheus Operator defaults for baseline scrape configuration.
		JobName:                        expectedPO.JobName,
		HonorLabels:                    gmp.HonorLabels,
		HonorTimestamps:                expectedPO.HonorTimestamps,
		TrackTimestampsStaleness:       gmp.TrackTimestampsStaleness,
		ScrapeInterval:                 gmp.ScrapeInterval,
		ScrapeTimeout:                  gmp.ScrapeTimeout,
		ScrapeProtocols:                expectedPO.ScrapeProtocols,
		MetricsPath:                    gmp.MetricsPath,
		Scheme:                         gmp.Scheme,
		Params:                         gmp.Params,
		SampleLimit:                    gmp.SampleLimit,
		LabelLimit:                     gmp.LabelLimit,
		LabelNameLengthLimit:           gmp.LabelNameLengthLimit,
		LabelValueLengthLimit:          gmp.LabelValueLengthLimit,
		EnableCompression:              true,
		TargetLimit:                    gmp.TargetLimit,
		BodySizeLimit:                  gmp.BodySizeLimit,
		KeepDroppedTargets:             gmp.KeepDroppedTargets,
		NativeHistogramBucketLimit:     gmp.NativeHistogramBucketLimit,
		NativeHistogramMinBucketFactor: gmp.NativeHistogramMinBucketFactor,
		HTTPClientConfig:               gmp.HTTPClientConfig,
	}

	// ScrapeTimeout: If omitted by the user, GMP defaults timeout = interval (e.g. 30s),
	// whereas Prometheus Operator's test server inherits a global 10s default.
	// If explicitly set by the user, gmp.ScrapeTimeout matches expectedPO.ScrapeTimeout directly.
	if gmp.ScrapeTimeout == gmp.ScrapeInterval && expectedPO.ScrapeTimeout != gmp.ScrapeTimeout {
		out.ScrapeTimeout = expectedPO.ScrapeTimeout
	}

	if out.Scheme == "" {
		out.Scheme = "http"
	}

	out.ServiceDiscoveryConfigs = expectedPO.ServiceDiscoveryConfigs
	out.RelabelConfigs = normalizeTargetRelabelConfigs(gmp.RelabelConfigs, gmp.MetricRelabelConfigs, expectedPO.RelabelConfigs, role, namespace, name, endpointPort, svcLabels)
	if len(expectedPO.MetricRelabelConfigs) > 0 {
		out.MetricRelabelConfigs = gmp.MetricRelabelConfigs
	}

	return out
}

// 5. Test Harness & Shared Fixture Helpers.

// newTestServiceFixture creates a standard test Service backing ServiceMonitor fixtures.
func newTestServiceFixture(name, namespace string, labels map[string]string) *corev1.Service {
	return &corev1.Service{
		TypeMeta:   metav1.TypeMeta{APIVersion: "v1", Kind: "Service"},
		ObjectMeta: metav1.ObjectMeta{Name: name, Namespace: namespace, Labels: labels},
		Spec: corev1.ServiceSpec{
			Selector: map[string]string{"app": "testpod"},
			Ports: []corev1.ServicePort{
				{Name: "web", Port: 80, TargetPort: intstr.FromString("web")},
			},
		},
	}
}

// testGoldenEquivalence executes inputs through the full Migrator / CLI pipeline,
// compiles the resulting GMP outputs with ScrapeConfigs(), and asserts 0-diff against raw upstream .golden files.
func testGoldenEquivalence(t *testing.T, goldenFileName string, inputs []runtime.Object, endpointPort string) {
	t.Helper()

	var (
		sdRole           = promk8s.RolePod
		primaryNamespace string
		primaryName      string
		svcLabels        map[string]string
	)

	var yamlBuf bytes.Buffer
	for _, in := range inputs {
		switch obj := in.(type) {
		case *pomonitoringv1.PodMonitor:
			sdRole = promk8s.RolePod
			primaryNamespace = obj.Namespace
			primaryName = obj.Name
			if obj.Kind == "" {
				obj.Kind = "PodMonitor"
				obj.APIVersion = "monitoring.coreos.com/v1"
			}
		case *pomonitoringv1.ServiceMonitor:
			sdRole = promk8s.RoleEndpoint
			primaryNamespace = obj.Namespace
			primaryName = obj.Name
			if obj.Kind == "" {
				obj.Kind = "ServiceMonitor"
				obj.APIVersion = "monitoring.coreos.com/v1"
			}
		case *corev1.Service:
			if obj.Kind == "" {
				obj.Kind = "Service"
				obj.APIVersion = "v1"
			}
			svcLabels = obj.Labels
		}

		data, err := k8syaml.Marshal(in)
		if err != nil {
			t.Fatalf("marshal input object error: %v", err)
		}
		if _, err := yamlBuf.WriteString("---\n"); err != nil {
			t.Fatalf("write YAML separator error: %v", err)
		}
		if _, err := yamlBuf.Write(data); err != nil {
			t.Fatalf("write YAML data error: %v", err)
		}
	}

	migrator := NewMigrator()
	migrator.RegisterConverter(&PodMonitorConverter{})
	migrator.RegisterConverter(&ServiceMonitorConverter{})
	migrator.Stdin = &yamlBuf
	migrator.Stderr = io.Discard

	report, err := migrator.Run("-")
	if err != nil {
		t.Fatalf("migrator.Run failed: %v", err)
	}
	if len(report.Outputs) == 0 {
		t.Fatal("no outputs produced by migrator")
	}

	// Iterate across all output resources and collect all compiled ScrapeConfigs.
	var allGMPScrapeCfgs []*config.ScrapeConfig
	for _, output := range report.Outputs {
		if output == nil {
			continue
		}
		switch output.GetKind() {
		case "PodMonitoring":
			var gmpPM monitoringv1.PodMonitoring
			if err := runtime.DefaultUnstructuredConverter.FromUnstructured(output.Object, &gmpPM); err != nil {
				t.Fatalf("FromUnstructured PodMonitoring error: %v", err)
			}
			// TODO: Inject mock Secret pool references into ScrapeConfigs() if future upstream test cases test
			// basicAuth, bearerToken, or TLS secret references against golden files.
			cfgs, err := gmpPM.ScrapeConfigs("test_project", "test_location", "test_cluster", nil)
			if err != nil {
				t.Fatalf("ScrapeConfigs error: %v", err)
			}
			allGMPScrapeCfgs = append(allGMPScrapeCfgs, cfgs...)
		case "ClusterPodMonitoring":
			var gmpCPM monitoringv1.ClusterPodMonitoring
			if err := runtime.DefaultUnstructuredConverter.FromUnstructured(output.Object, &gmpCPM); err != nil {
				t.Fatalf("FromUnstructured ClusterPodMonitoring error: %v", err)
			}
			cfgs, err := gmpCPM.ScrapeConfigs("test_project", "test_location", "test_cluster", nil)
			if err != nil {
				t.Fatalf("ScrapeConfigs error: %v", err)
			}
			allGMPScrapeCfgs = append(allGMPScrapeCfgs, cfgs...)
		}
	}

	goldenPath := filepath.Join("testdata", "golden", goldenFileName)
	goldenData, err := os.ReadFile(goldenPath)
	if err != nil {
		t.Fatalf("cannot read golden file %s: %v", goldenPath, err)
	}
	var poPromCfg config.Config
	if err := yaml.Unmarshal(goldenData, &poPromCfg); err != nil {
		t.Fatalf("unmarshaling golden file: %v", err)
	}
	if len(poPromCfg.ScrapeConfigs) == 0 {
		t.Fatalf("no scrape configs found in %s", goldenFileName)
	}

	if len(allGMPScrapeCfgs) != len(poPromCfg.ScrapeConfigs) {
		// TODO: If future upstream test cases evaluate multi-namespace namespaceSelector fixtures against golden files,
		// add multi-ScrapeConfig aggregation to reconcile GMP's split PodMonitoring CRDs against PO's single ScrapeConfig.
		t.Fatalf("scrape config count mismatch: got %d, want %d", len(allGMPScrapeCfgs), len(poPromCfg.ScrapeConfigs))
	}

	for i, expectedPO := range poPromCfg.ScrapeConfigs {
		normalizedGMP := normalizeGMPScrapeConfig(allGMPScrapeCfgs[i], expectedPO, sdRole, primaryNamespace, primaryName, endpointPort, svcLabels)

		poYAML, err := yaml.Marshal(expectedPO)
		if err != nil {
			t.Fatalf("marshal PO YAML error: %v", err)
		}
		gmpYAML, err := yaml.Marshal(normalizedGMP)
		if err != nil {
			t.Fatalf("marshal GMP YAML error: %v", err)
		}

		if diff := cmp.Diff(string(poYAML), string(gmpYAML)); diff != "" {
			t.Errorf("normalized GMP scrape config [%d] mismatch with raw PO golden (-PO, +GMP):\n%s", i, diff)
		}
	}
}

// 6. PodMonitor Test Suite.

// TestPodTargetLabelsFromPodMonitor mirrors upstream TestPodTargetLabelsFromPodMonitor in promcfg_test.go.
func TestPodTargetLabelsFromPodMonitor(t *testing.T) {
	pm := &pomonitoringv1.PodMonitor{
		TypeMeta: metav1.TypeMeta{APIVersion: "monitoring.coreos.com/v1", Kind: "PodMonitor"},
		ObjectMeta: metav1.ObjectMeta{
			Name:      "testpodmonitor1",
			Namespace: "default",
			Labels: map[string]string{
				"group": "group1",
			},
		},
		Spec: pomonitoringv1.PodMonitorSpec{
			PodTargetLabels: []string{"example", "env"},
			PodMetricsEndpoints: []pomonitoringv1.PodMetricsEndpoint{
				{
					Port:     "web",
					Interval: "30s",
				},
			},
		},
	}
	testGoldenEquivalence(t, "PodTargetLabelsFromPodMonitor.golden", []runtime.Object{pm}, "web")
}

// TestPodMonitorPhaseFilter mirrors upstream TestPodMonitorPhaseFilter in promcfg_test.go.
func TestPodMonitorPhaseFilter(t *testing.T) {
	pm := &pomonitoringv1.PodMonitor{
		TypeMeta: metav1.TypeMeta{APIVersion: "monitoring.coreos.com/v1", Kind: "PodMonitor"},
		ObjectMeta: metav1.ObjectMeta{
			Name:      "testpodmonitor1",
			Namespace: "default",
			Labels: map[string]string{
				"group": "group1",
			},
		},
		Spec: pomonitoringv1.PodMonitorSpec{
			PodMetricsEndpoints: []pomonitoringv1.PodMetricsEndpoint{
				{
					FilterRunning: ptr.To(false),
					Port:          "test",
				},
			},
		},
	}
	testGoldenEquivalence(t, "PodMonitorPhaseFilter.golden", []runtime.Object{pm}, "test")
}

// 7. ServiceMonitor Test Suite.

// TestTargetLabels mirrors upstream TestTargetLabels in promcfg_test.go.
func TestTargetLabels(t *testing.T) {
	sm := &pomonitoringv1.ServiceMonitor{
		TypeMeta: metav1.TypeMeta{APIVersion: "monitoring.coreos.com/v1", Kind: "ServiceMonitor"},
		ObjectMeta: metav1.ObjectMeta{
			Name:      "testservicemonitor1",
			Namespace: "default",
		},
		Spec: pomonitoringv1.ServiceMonitorSpec{
			TargetLabels: []string{"example", "env"},
			Endpoints: []pomonitoringv1.Endpoint{
				{
					Port:     "web",
					Interval: "30s",
				},
			},
		},
	}
	svc := newTestServiceFixture("testservicemonitor1", "default", map[string]string{"group": "group1", "example": "example-val", "env": "prod"})
	testGoldenEquivalence(t, "TargetLabels.golden", []runtime.Object{sm, svc}, "web")
}

// TestPodTargetLabels mirrors upstream TestPodTargetLabels in promcfg_test.go for ServiceMonitor.
func TestPodTargetLabels(t *testing.T) {
	sm := &pomonitoringv1.ServiceMonitor{
		TypeMeta: metav1.TypeMeta{APIVersion: "monitoring.coreos.com/v1", Kind: "ServiceMonitor"},
		ObjectMeta: metav1.ObjectMeta{
			Name:      "testservicemonitor1",
			Namespace: "default",
			Labels: map[string]string{
				"group": "group1",
			},
		},
		Spec: pomonitoringv1.ServiceMonitorSpec{
			PodTargetLabels: []string{"example", "env"},
			Endpoints: []pomonitoringv1.Endpoint{
				{
					Port:     "web",
					Interval: "30s",
				},
			},
		},
	}
	svc := newTestServiceFixture("testservicemonitor1", "default", map[string]string{"group": "group1", "example": "example-val", "env": "prod"})
	testGoldenEquivalence(t, "PodTargetLabels.golden", []runtime.Object{sm, svc}, "web")
}
