version: 2
updates:
- package-ecosystem: docker
  directory: /hack
  schedule:
    interval: weekly
- package-ecosystem: docker
  directory: /cmd/rule-evaluator
  schedule:
    interval: weekly
- package-ecosystem: docker
  directory: /cmd/operator
  schedule:
    interval: weekly
- package-ecosystem: docker
  directory: /cmd/frontend
  schedule:
    interval: weekly
- package-ecosystem: docker
  directory: /cmd/config-reloader
  schedule:
    interval: weekly
- package-ecosystem: gomod
  directory: /
  schedule:
    interval: weekly
  groups:
    # Group dep updates into one PR as single update already updates co-located deps.
    # Skip biggest and the most complex deps: Thanos and Prometheus.
    go-deps:
      patterns:
        - "*"
      exclude-patterns:
        - "github.com/thanos-io/thanos"
        - "github.com/prometheus/prometheus"
