policies:
  - type: commit
    spec:
      header:
        length: 89
        imperative: true
        case: lower
        invalidLastCharacters: .
      body:
        required: true
      spellcheck:
        locale: US
      maximumOfOneCommit: false
      conventional:
        # Consistent with @commitlint/config-conventional, as referenced in Conventional Commits Specification.
        # https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional#type-enum
        types:
          - "build"
          - "chore"
          - "ci"
          - "docs"
          - "perf"
          - "refactor"
          - "revert"
          - "style"
          - "test"
        scopes:
          - "operator"
        descriptionLength: 72
