# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: "2"
linters:
  default: all
  disable:
    - containedctx
    - contextcheck
    - cyclop
    - depguard
    - err113
    - errorlint
    - exhaustive
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godox
    - gomoddirectives
    - gosec
    - inamedparam
    - ireturn
    - lll
    - maintidx
    - mnd
    - nestif
    - nilnil
    - nlreturn
    - noctx
    - noinlineerr
    # TODO(bwplotka): Remove once https://github.com/golangci/golangci-lint/issues/3228 is fixed.
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - protogetter
    - tagliatelle
    - testpackage
    - thelper
    - tparallel
    - unparam
    - varnamelen
    - wastedassign
    - wrapcheck
    - wsl
    - wsl_v5
  settings:
    errcheck:
      # Report about not checking of errors in type assertions: `a := b.(MyStruct)`.
      # Such cases aren't reported by default.
      # Default: false
      check-type-assertions: false
      # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`.
      # Such cases aren't reported by default.
      # Default: false
      check-blank: false
      # To disable the errcheck built-in exclude list.
      # See `-excludeonly` option in https://github.com/kisielk/errcheck#excluding-functions for details.
      # Default: false
      disable-default-exclusions: false
      # List of functions to exclude from checking, where each entry is a single function to exclude.
      # See https://github.com/kisielk/errcheck#excluding-functions for details.
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
        - fmt.Print
        - fmt.Printf
        - fmt.Println
        - io/ioutil.ReadFile
        - io.Copy(*bytes.Buffer)
        - io.Copy(os.Stdout)
      # Display function signature instead of selector.
      # Default: false
      verbose: true
    importas:
      alias:
        - pkg: k8s.io/api/apps/v1
          alias: appsv1
        - pkg: k8s.io/api/meta/v1
          alias: metav1
        - pkg: k8s.io/apimachinery/pkg/api/errors
          alias: apierrors
        - pkg: github.com/GoogleCloudPlatform/prometheus-engine/pkg/operator/apis/monitoring/v1
          alias: monitoringv1
      no-unaliased: true
    modernize:
      disable:
      - omitzero
    revive:
      enable-all-rules: true
      rules:
        - name: add-constant
          arguments:
            - allowFloats: 0.0,0.,1.0,1.,2.0,2.
              allowInts: 0,1,2
              allowStrs: '""'
              maxLitCount: "3"
          severity: warning
          disabled: true
        - name: cognitive-complexity
          arguments:
            - 7
          severity: warning
          disabled: true
        - name: confusing-naming
          severity: warning
          disabled: true
        - name: cyclomatic
          arguments:
            - 3
          severity: warning
          disabled: true
        - name: defer
          severity: warning
          disabled: true
        - name: duplicated-imports
          severity: warning
          disabled: true
        - name: exported
          arguments:
            - checkPrivateReceivers
            - disableStutteringCheck
            - sayRepetitiveInsteadOfStutters
          severity: warning
          disabled: true
        - name: flag-parameter
          severity: warning
          disabled: true
        - name: function-length
          arguments:
            - 10
            - 0
          severity: warning
          disabled: true
        - name: function-result-limit
          arguments:
            - 2
          severity: warning
          disabled: true
        - name: if-return
          severity: warning
          disabled: true
        - name: import-alias-naming
          arguments:
            - ^[a-z][a-z0-9]{0,}$
          severity: warning
          disabled: true
        - name: import-shadowing
          severity: warning
          disabled: true
        - name: line-length-limit
          arguments:
            - 80
          severity: warning
          disabled: true
        - name: max-public-structs
          arguments:
            - 3
          severity: warning
          disabled: true
        - name: package-comments
          severity: warning
          disabled: true
        - name: range-val-address
          severity: warning
          disabled: true
        - name: redundant-import-alias
          severity: warning
          disabled: true
        - name: struct-tag
          arguments:
            - json,inline
            - bson,outline,gnu
          severity: warning
          disabled: true
        - name: time-equal
          severity: warning
          disabled: true
        - name: unchecked-type-assertion
          severity: warning
          disabled: true
        - name: unhandled-error
          severity: warning
          disabled: false
          exclude: [""]
          arguments:
            - "fmt.Fprint"
            - "fmt.Fprintf"
            - "fmt.Fprintln"
            - "fmt.Print"
            - "fmt.Printf"
            - "fmt.Println"
            - "strings.Builder.WriteByte"
        - name: unused-receiver
          arguments:
            - allowRegex: ^_
          severity: warning
          disabled: true
        - name: use-any
          severity: warning
          disabled: true
        - name: useless-break
          severity: warning
          disabled: true
        - name: enforce-switch-style
          severity: warning
          disabled: true
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
        path: _test\.go
      - path: (.+)\.go$
        text: Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
