# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# The release/0.12 linter is set to a minimal maintnance mode.
# Code style & non-critical issues should be resolved in
# main to prevent accidental breakage.

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - staticcheck
    - typecheck
    - unused
    - gosimple
    - ineffassign

linters-settings:
  importas:
    no-unaliased: true
    alias:
    - pkg: "k8s.io/api/apps/v1"
      alias: appsv1
    - pkg: "k8s.io/api/meta/v1"
      alias: metav1
    - pkg: "k8s.io/apimachinery/pkg/api/errors"
      alias: apierrors
    - pkg: "github.com/GoogleCloudPlatform/prometheus-engine/pkg/operator/apis/monitoring/v1"
      alias: monitoringv1
issues:
  exclude-use-default: false
  exclude:
    # errcheck: Almost all programs ignore errors on these functions and in most cases it's ok
    # Allow ignore errors on stdout/stderr/printing
    - 'Error return value of .((os\.)?std(out|err)\..*|.*printf?). is not checked'
    # Allow ignore errors on Close/Flush
    - 'Error return value of .*Close. is not checked'
    - 'Error return value of .*Flush. is not checked'
    # Allow ignore errors on Remove/Setenv
    - 'Error return value of os\.Remove(All)?. is not checked'
    - 'Error return value of os\.(Un)?Setenv. is not checked'
