# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
steps:

- name: 'gcr.io/cloud-builders/docker'
  id: 'build-frontend-buildx'
  args: ['buildx', 'create', '--name=buildx-frontend-builder', '--driver=docker-container', '--driver-opt', 'network=cloudbuild', '--use']
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-frontend'
  waitFor: ['build-frontend-buildx']
  args: ['buildx', 'build', '-f', 'cmd/frontend/Dockerfile', '.', '--platform', 'linux/arm64,linux/amd64', '-t', 'gcr.io/$PROJECT_ID/prometheus-engine/frontend:$TAG_NAME', '--push']
  timeout: 1200s

- name: 'gcr.io/cloud-builders/docker'
  id: 'build-config-reloader-buildx'
  args: ['buildx', 'create', '--name=buildx-config-reloader-builder', '--driver=docker-container', '--driver-opt', 'network=cloudbuild', '--use']
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-config-reloader'
  waitFor: ['build-config-reloader-buildx']
  args: ['buildx', 'build', '-f', 'cmd/config-reloader/Dockerfile', '.', '--platform', 'linux/arm64,linux/amd64', '-t', 'gcr.io/$PROJECT_ID/prometheus-engine/config-reloader:$TAG_NAME', '--push']
  timeout: 1200s

- name: 'gcr.io/cloud-builders/docker'
  id: 'build-rule-evaluator-buildx'
  args: ['buildx', 'create', '--name=buildx-rule-evaluator-builder', '--driver=docker-container', '--driver-opt', 'network=cloudbuild', '--use']
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-rule-evaluator'
  waitFor: ['build-rule-evaluator-buildx']
  args: ['buildx', 'build', '-f', 'cmd/rule-evaluator/Dockerfile', '.', '--platform', 'linux/arm64,linux/amd64', '-t', 'gcr.io/$PROJECT_ID/prometheus-engine/rule-evaluator:$TAG_NAME', '--push']
  timeout: 1200s

- name: 'gcr.io/cloud-builders/docker'
  id: 'build-operator-buildx'
  args: ['buildx', 'create', '--name=buildx-operator-builder', '--driver=docker-container', '--driver-opt', 'network=cloudbuild', '--use']
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-operator'
  waitFor: ['build-operator-buildx']
  args: ['buildx', 'build', '-f', 'cmd/operator/Dockerfile', '.', '--platform', 'linux/arm64,linux/amd64', '-t', 'gcr.io/$PROJECT_ID/prometheus-engine/operator:$TAG_NAME', '--push']
  timeout: 1200s

options:
  env:
    - DOCKER_CLI_EXPERIMENTAL=enabled
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: '200'

timeout: 4800s