# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-config-reloader'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/prometheus-engine/config-reloader:$TAG_NAME', '-f', 'cmd/config-reloader/Dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-rule-evaluator'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/prometheus-engine/rule-evaluator:$TAG_NAME', '-f', 'cmd/rule-evaluator/Dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-operator'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/prometheus-engine/operator:$TAG_NAME', '-f', 'cmd/operator/Dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-frontend'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/prometheus-engine/frontend:$TAG_NAME', '-f', 'cmd/frontend/Dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-example-app'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/prometheus-engine/example-app:$TAG_NAME', '-f', 'cmd/example-app/Dockerfile', '.']

images:
- 'gcr.io/$PROJECT_ID/prometheus-engine/config-reloader:$TAG_NAME'
- 'gcr.io/$PROJECT_ID/prometheus-engine/rule-evaluator:$TAG_NAME'
- 'gcr.io/$PROJECT_ID/prometheus-engine/operator:$TAG_NAME'
- 'gcr.io/$PROJECT_ID/prometheus-engine/frontend:$TAG_NAME'
- 'gcr.io/$PROJECT_ID/prometheus-engine/example-app:$TAG_NAME'