steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-config-reloader'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/gpe-config-reloader:$TAG_NAME', '-f', 'cmd/config-reloader/Dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-operator'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/gpe-operator:$TAG_NAME', '-f', 'cmd/operator/Dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-example-app'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/example-app:$TAG_NAME', '-f', 'cmd/example-app/Dockerfile', '.']

images:
- 'gcr.io/$PROJECT_ID/gpe-config-reloader:$TAG_NAME'
- 'gcr.io/$PROJECT_ID/gpe-operator:$TAG_NAME'
- 'gcr.io/$PROJECT_ID/example-app:$TAG_NAME'