# Collector ClusterRole definition based on the following manifests
# https://github.com/GoogleCloudPlatform/prometheus-engine/blob/v0.1.1/examples/operator.yaml#L46

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Namespace }}:collector
rules:
- apiGroups: [""]
  resources:
  - endpoints
  - nodes
  - nodes/metrics
  - pods
  - services
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
