# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-synthetic
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: "go-synthetic"
  template:
    metadata:
      labels:
        app: "go-synthetic"
    spec:
      containers:
      - name: go-synthetic
        # TODO(bwplotka): Move to go-synthetic image once released.
        image: us-central1-docker.pkg.dev/gpe-test-1/dhrabovcak/example-app@sha256:e57d6743394a39dbf0ce111a287a829dbcd1ee6632294132f28ab6f01f12d78d
        args:
        - "--listen-address=:8080"
        - "--cpu-burn-ops=75"
        - "--memory-ballast-mbs=1024"
        env:
        # Needed when using --tls-create-self-signed
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - name: web
          containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
          limits:
            memory: 10000Mi
      terminationGracePeriodSeconds: 5
---
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: go-synthetic
spec:
  selector:
    matchLabels:
      app: go-synthetic
  endpoints:
  - port: 8080
    interval: 15s
