apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: jenkins
  labels:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/part-of: google-cloud-managed-prometheus
spec:
  endpoints:
  - port: http
    scheme: http
    interval: 30s
    path: /prometheus
  selector:
    matchLabels:
      app.kubernetes.io/name: jenkins
