# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: monitoring.googleapis.com/v1
kind: Rules
metadata:
  name: kibana-rules
  labels:
    app.kubernetes.io/component: rules
    app.kubernetes.io/name: kibana-rules
    app.kubernetes.io/part-of: google-cloud-managed-prometheus
spec:
  groups:
  - name: kibana
    interval: 30s
    rules:
    - alert: KibanaHighCPUUsage
      annotations:
        description: |-
          Kibana high cpu usage
            VALUE = {{ $value }}
            LABELS: {{ $labels }}
        summary: Kibana high cpu usage (instance {{ $labels.instance }})
      expr: kibana_os_load5 >= 90
      for: 5m
      labels:
        severity: critical
    - alert: KibanaHighMemoryUsage
      annotations:
        description: |-
          Kibana high memory usage
            VALUE = {{ $value }}
            LABELS: {{ $labels }}
        summary: Kibana high memory usage (instance {{ $labels.instance }})
      expr: kibana_os_mem_bytes_used / kibana_os_mem_bytes_total >= 0.9
      for: 5m
      labels:
        severity: critical
