#!/usr/bin/env bash

# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail

combine() {
  SOURCE_DIR=$1
  DEST_YAML=$2

  YAMLS=$(find ${SOURCE_DIR} -regextype sed -regex '^.*/[0-9][0-9]-\w.*.yaml$' | sort)
  cat "${SCRIPT_ROOT}"/hack/boilerplate.txt > $DEST_YAML
  echo -e "# NOTE: This file is autogenerated.\n" >> $DEST_YAML
  sed -s '$a---' $YAMLS | sed -e '$ d' -e '/^#/d' -e '/^$/d' >> $DEST_YAML
}

SCRIPT_ROOT=$(dirname "${BASH_SOURCE[0]}")/..

combine ${SCRIPT_ROOT}/cmd/operator/deploy/operator ${SCRIPT_ROOT}/examples/operator.yaml
combine ${SCRIPT_ROOT}/cmd/operator/deploy/rule-evaluator ${SCRIPT_ROOT}/examples/rule-evaluator.yaml
