# Static manifests for deployment and use by the operator.
apiVersion: v1
kind: Namespace
metadata:
  name: gpe-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: gpe-system
  name: collector
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gpe-collector
subjects:
- kind: ServiceAccount
  namespace: gpe-system
  name: collector