# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

commonLabels: false
namespace:
  public: gmp-public
  system: gmp-system
version: 0.13.0
images:
  bash:
    image: gke.gcr.io/gke-distroless/bash
    tag: "gke_distroless_20240607.00_p0" # NOTE: Has to be quoted otherwise it will be treated as a number.
  alertmanager:
    image: gke.gcr.io/prometheus-engine/alertmanager@sha256
    tag: "4311da6164f66c4097878c023d4aa5ab908641414e087ba4d5eb29b6126158bc"
  prometheus:
    # TODO(bwplotka): Change to "v2.45.3-gmp.6-gke.0" once tags are cloned.
    image: gke.gcr.io/prometheus-engine/prometheus@sha256
    tag: "8c8e35af7e2b92ac9d82ce640621c0d3aa10d7d62856681af3572d0a8fbb787b"
  configReloader:
    image: gke.gcr.io/prometheus-engine/config-reloader@sha256
    tag: "21055a361185da47fbd2c21389fb5cd00b54bfed5c784e0dc258b5b416beaf7e"
  operator:
    image: gke.gcr.io/prometheus-engine/operator@sha256
    tag: "0894c65806a6eac0b4119ee73ec8a52f6ca119960b37aded3776f3748a75d182"
  ruleEvaluator:
    image: gke.gcr.io/prometheus-engine/rule-evaluator@sha256
    tag: "6ae997a8ed636da06b7a9dc7fc950b98ce91c38c135aad2dcc95d6d3dd841ee0"
  datasourceSyncer:
    image: gcr.io/gke-release/prometheus-engine/datasource-syncer@sha256
    tag: "f065e90e3188ee3fd858cac74a8ed326446aaed51d1f222f29ebd5f7b29d1df7"
maxThroughput: false
resources:
  alertManager:
    limits:
      memory: 128M
    requests:
      cpu: 1m
      memory: 16M
  bash:
    limits:
      memory: 32M
    requests:
      cpu: 1m
      memory: 4M
  collector:
    limits:
      memory: 2G
    requests:
      cpu: 4m
      memory: 32M
  configReloader:
    limits:
      memory: 32M
    requests:
      cpu: 1m
      memory: 4M
  operator:
    limits:
      memory: 2G
    requests:
      cpu: 1m
      memory: 16M
  ruleEvaluator:
    limits:
      memory: 1G
    requests:
      cpu: 1m
      memory: 16M
deployOperator: true
tls:
  base64:
    ca: null
    cert: null
    key: null
collector:
  rbac:
    create: true
  serviceAccount:
    create: true
operator:
  rbac:
    create: true
  serviceAccount:
    create: true
ruleEvaluator:
  rbac:
    create: true
  serviceAccount:
    create: true
    name: rule-evaluator
