# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-receiver
  namespace: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-receiver
  template:
    metadata:
      labels:
        app: prometheus-receiver
    spec:
      containers:
        - name: prometheus
          image: quay.io/prometheus/prometheus
          args:
          - --web.enable-remote-write-receiver
          - --config.file=/etc/prometheus/prometheus.yml
          - --web.listen-address=:9090
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-cfg
            defaultMode: 420
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-receiver
  namespace: prometheus
spec:
  clusterIP: None
  selector:
    app: prometheus-receiver
  ports:
    - name: web
      port: 9090
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-cfg
  namespace: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']