# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: monitoring.googleapis.com/v1
kind: Rules
metadata:
  name: nginx-rules
  labels:
    app.kubernetes.io/component: rules
    app.kubernetes.io/name: nginx-rules
    app.kubernetes.io/part-of: google-cloud-managed-prometheus
spec:
  groups:
  - name: nginx
    interval: 30s
    rules:
    - alert: NginxDown
      annotations:
        description: |-
          Nginx instance is down
            VALUE = {{ $value }}
            LABELS: {{ $labels }}
        summary: Nginx down (instance {{ $labels.instance }})
      expr: nginx_up{job="nginx"} == 0
      for: 5m
      labels:
        severity: critical
    - alert: NginxDroppedConnections
      annotations:
        description: |-
         Too many dropped connections (> 5%)
            VALUE = {{ $value }}
            LABELS: {{ $labels }}
        summary: Number of dropped connections is high (instance {{ $labels.instance }})
      expr: (rate(nginx_connections_accepted{job="nginx"}[1m]) - rate(nginx_connections_handled{job="nginx"}[1m])) / rate(nginx_connections_accepted{job="nginx"}[1m]) > 0.05
      for: 5m
      labels:
        severity: warning
    - alert: NginxTrafficSpike
      annotations:
        description: |-
          Increase in total number of HTTP requests received (> 20%)
            VALUE = {{ $value }}
            LABELS: {{ $labels }}
        summary: Spike in HTTP traffic (instance {{ $labels.instance }})
      expr: rate(nginx_http_requests_total{job="nginx"}[1m])/ rate(nginx_http_requests_total{job="nginx"}[1m] offset 5m) > 1.2
      for: 5m
      labels:
        severity: warning
    - alert: NginxTrafficDrop
      annotations:
        description: |-
           Decrease in total number of HTTP requests received (> 20%)
            VALUE = {{ $value }}
            LABELS: {{ $labels }}
        summary: Drop in HTTP traffic (instance {{ $labels.instance }})
      expr: rate(nginx_http_requests_total{job="nginx"}[1m])/ rate(nginx_http_requests_total{job="nginx"}[1m] offset 5m) < 0.8
      for: 5m
      labels:
        severity: warning
