# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: example-app-${INDEX}
  labels: 
    app.kubernetes.io/name: example-app
    app.kubernetes.io/instance: "instance-${INDEX}"
spec:
  replicas: ${REPLICAS}
  selector:
    matchLabels:
      app.kubernetes.io/name: example-app
      app.kubernetes.io/instance: "instance-${INDEX}"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: example-app
        app.kubernetes.io/instance: "instance-${INDEX}"
    spec:
      containers:
      - name: example-app
        image: "gcr.io/${PROJECT_ID}/example-app:${IMAGE_TAG}"
        args:
        - "--listen-address=:8080"
        - "--max-count=32"
        - "--cpu-burn-ops=${CPU_BURN}"
        - "--memory-ballast-mbs=${MEM_BALLAST}"
        ports:
        - name: web
          containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
          limits:
            memory: 10000Mi
      terminationGracePeriodSeconds: 5
