apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: example-app-${INDEX}
  labels: 
    app.kubernetes.io/name: example-app
    app.kubernetes.io/instance: "instance-${INDEX}"
spec:
  replicas: ${REPLICAS}
  selector:
    matchLabels:
      app.kubernetes.io/name: example-app
      app.kubernetes.io/instance: "instance-${INDEX}"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: example-app
        app.kubernetes.io/instance: "instance-${INDEX}"
    spec:
      containers:
      - name: example-app
        image: "gcr.io/${PROJECT_ID}/example-app:${IMAGE_TAG}"
        args:
        - "--listen-address=:8080"
        - "--max-count=32"
        - "--cpu-burn-ops=${CPU_BURN}"
        - "--memory-ballast-mbs=${MEM_BALLAST}"
        ports:
        - name: web
          containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
          limits:
            memory: 10000Mi
      terminationGracePeriodSeconds: 5
