# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: monitoring.googleapis.com/v1
kind: Rules
metadata:
  name: rabbitmq-rules
  labels:
    app.kubernetes.io/component: rules
    app.kubernetes.io/name: rabbitmq-rules
    app.kubernetes.io/part-of: google-cloud-managed-prometheus
spec:
  groups:
  - name: rabbitmq
    interval: 30s
    rules:
    - alert: RabbitMQHighUnacknowledgedMessages
      annotations:
        description: |-
          RabbitMQ high unacknowledged messages
            VALUE = {{ $value }}
            LABELS: {{ $labels }}
        summary: RabbitMQ high unacknowledged messages (instance {{ $labels.instance }})
      expr: rabbitmq_channel_messages_unacked > 5
      for: 5m
      labels:
        severity: critical
    - alert: RabbitMQHighUnroutableMessages
      annotations:
        description: |-
          RabbitMQ high unroutable messages
            VALUE = {{ $value }}
            LABELS: {{ $labels }}
        summary: RabbitMQ high unroutable messages (instance {{ $labels.instance }})
      expr: rate(rabbitmq_channel_messages_unroutable_dropped_total[5m]) > 0
      for: 5m
      labels:
        severity: warning
    - alert: RabbitMQLowDeliveredMessages
      annotations:
        description: |-
          RabbitMQ low delivered messages
            VALUE = {{ $value }}
            LABELS: {{ $labels }}
        summary: RabbitMQ low delivered messages (instance {{ $labels.instance }})
      expr: rate(rabbitmq_channel_messages_delivered_total[5m]) < 10
      for: 5m
      labels:
        severity: warning
