# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Static manifests for deployment and use by the operator.
apiVersion: v1
kind: Namespace
metadata:
  name: gpe-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: gpe-system
  name: operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gpe-system:operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gpe-system:operator
subjects:
- kind: ServiceAccount
  namespace: gpe-system
  name: operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gpe-system:operator-csr
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gpe-system:csr-approver
subjects:
- kind: ServiceAccount
  namespace: gpe-system
  name: operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gpe-system
  name: gpe-operator
  labels:
    app.kubernetes.io/name: gpe-operator
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: gpe
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gpe-operator
      app.kubernetes.io/component: operator
      app.kubernetes.io/part-of: gpe
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gpe-operator
        app.kubernetes.io/component: operator
        app.kubernetes.io/part-of: gpe
    spec:
      serviceAccountName: operator
      containers:
      - name: operator
        image: "gcr.io/gpe-test-1/gpe-operator:bench_20210508_1502"
        args:
        - "--priority-class=gpe-critical"
        - "--ca-selfsign=false"
        ports:
        - name: webhook
          # Note this should match the --listen-addr flag passed in to the operator args.
          # Default is 8443.
          containerPort: 8443
        - name: metrics
          # Note this should match the --metrics-addr flag passed in to the operator args.
          # Default is 18080.
          containerPort: 18080
---
apiVersion: v1
kind: Service
metadata:
  namespace: gpe-system
  name: gpe-operator
spec:
  selector:
    app.kubernetes.io/name: gpe-operator
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: gpe
  ports:
    - protocol: TCP
      port: 443
      targetPort: webhook
