apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: servicemonitorings.monitoring.googleapis.com
spec:
  group: monitoring.googleapis.com
  version: v1alpha1
  names:
    kind: ServiceMonitoring
    plural: servicemonitorings
  scope: Namespaced
  subresources:
    status: {}
