# Static manifests for deployment and use by the operator.
apiVersion: v1
kind: Namespace
metadata:
  name: gpe-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: gpe-system
  name: operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gpe-system:operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gpe-system:operator
subjects:
- kind: ServiceAccount
  namespace: gpe-system
  name: operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gpe-system:operator-csr
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gpe-system:csr-approver
subjects:
- kind: ServiceAccount
  namespace: gpe-system
  name: operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gpe-system
  name: gpe-operator
  labels:
    app.kubernetes.io/name: gpe-operator
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: gpe
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gpe-operator
      app.kubernetes.io/component: operator
      app.kubernetes.io/part-of: gpe
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gpe-operator
        app.kubernetes.io/component: operator
        app.kubernetes.io/part-of: gpe
    spec:
      serviceAccountName: operator
      containers:
      - name: operator
        image: "gcr.io/gpe-test-1/gpe-operator:bench_20213003_2100"
        args:
        - "--priority-class=gpe-critical"
        - "--cloud-monitoring-endpoint=staging-monitoring.sandbox.googleapis.com:443"
        - "--kubeconfig="
        - "--ca-selfsign=false"
        ports:
        - name: webhook
          # Note this should match the --listen-addr flag passed in to the operator args.
          # Default is 8443.
          containerPort: 8443
---
apiVersion: v1
kind: Service
metadata:
  namespace: gpe-system
  name: gpe-operator
spec:
  selector:
    app.kubernetes.io/name: gpe-operator
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: gpe
  ports:
    - protocol: TCP
      port: 443
      targetPort: webhook