apiVersion: v1
kind: ConfigMap
metadata:
  namespace: gpe-system
  name: scrape-kube-state-metrics
  labels:
    type: scrape-config
    app.kubernetes.io/name: kube-state-metrics
data:
  config.yaml: |
    # The resource state metrics typically have a namespace associated, which we want to use
    # rather than the typical target label 'namespace', which merely contains the namespace of the
    # KSM pod.
    # To ensure the namespace is left empty, we use this hard-coded configuration.
    
    # Scraping of KSM's process metrics is configured via PodMonitoring.

    scrape_configs:
    - job_name: kube-state-metrics/metrics
      scrape_interval: 30s
      scrape_timeout: 30s
      metrics_path: /metrics
      honor_labels: true
      kubernetes_sd_configs:
      - role: pod
        selectors:
        - role: pod
          field: spec.nodeName=$(NODE_NAME)
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_node_name]
        regex: $(NODE_NAME)
        action: keep
      - source_labels: [__meta_kubernetes_namespace]
        regex: gpe-system
        action: keep
      - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
        regex: kube-state-metrics
        action: keep
      - target_label: job
        replacement: kube-state-metrics
        action: replace
      - source_labels: [__meta_kubernetes_pod_name, __meta_kubernetes_pod_container_port_name]
        regex: (.+);(.+)
        target_label: instance
        replacement: $1:$2
        action: replace
      - source_labels: [__meta_kubernetes_pod_container_port_name]
        regex: metrics
        action: keep