apiVersion: v1
kind: Service
metadata:
  namespace: gpe-system
  name: kube-state-metrics
  labels:
    app.kubernetes.io/name: kube-state-metrics
spec:
  selector:
    app.kubernetes.io/name: kube-state-metrics
  clusterIP: None
  ports:
  - name: metrics
    port: 8000
    targetPort: metrics
  - name: metrics-self
    port: 8001
    targetPort: metrics-self