apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: velero
  labels:
    app.kubernetes.io/name: velero
    app.kubernetes.io/part-of: google-cloud-managed-prometheus
spec:
  endpoints:
  - port: metrics
    scheme: http
    interval: 30s
    path: /metrics
  selector:
    matchLabels:
      deploy: velero
