# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: monitoring.googleapis.com/v1
kind: Rules
metadata:
  name: velero-rules
  labels:
    app.kubernetes.io/component: rules
    app.kubernetes.io/name: velero-rules
    app.kubernetes.io/part-of: google-cloud-managed-prometheus
spec:
  groups:
  - name: velero
    interval: 30s
    rules:
    - alert: VeleroBackupFailure
      annotations:
        description: |-
          Velero backup failure
            VALUE = {{ $value }}
            LABELS: {{ $labels }}
        summary: Velero backup failure (instance {{ $labels.instance }})
      expr: velero_backup_failure_total > 0
      for: 5m
      labels:
        severity: critical
    - alert: VeleroPartialBackupFailure
      annotations:
        description: |-
          Velero partial backup failure
            VALUE = {{ $value }}
            LABELS: {{ $labels }}
        summary: Velero partial backup failure (instance {{ $labels.instance }})
      expr: velero_backup_partial_failure_total > 0
      for: 5m
      labels:
        severity: warning
    - alert: VeleroRestoreFailure
      annotations:
        description: |-
          Velero restore failure
            VALUE = {{ $value }}
            LABELS: {{ $labels }}
        summary: Velero restore failure (instance {{ $labels.instance }})
      expr: velero_restore_failed_total > 0
      for: 5m
      labels:
        severity: critical
