name: Issue assignment

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
    - name: Auto-assign issue
      uses: pozil/auto-assign-issue@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        assignees: ${{ secrets.DEFAULT_ISSUE_ASSIGNEE }}
        abortIfPreviousAssignees: true
