name: Auto Assign PR

# This job triggers privileged auto-assign job in secure manner.
# See: https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  schedule:
    runs-on: ubuntu-latest
    steps:
    - name: Pass parameters to Auto Assign job
      run: |
        mkdir -p ./pr
        echo ${{ github.event.number }} > ./pr/NR
    - uses: actions/upload-artifact@v3
      with:
        name: auto-assign-pr
        path: pr/
    - run: echo "Scheduled!"
